version: '3.8'

services:
  jenkins_app:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins_app
    ports:
      - "8081:8080" # для доступа к веб-интерфейсу Jenkins
      - "50000:50000" # для подключения агентов
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_ntwrk

  persistence_app:
    build: .
    container_name: persistence_app
    env_file:
      - 'variables.env'
    ports:
      - "8082:8080"
    networks:
      - persistence_ntwrk
  postgres_db:
    container_name: postgres_db
    image: postgres
    env_file:
      - 'variables.env'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    networks:
      - persistence_ntwrk
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - persistence_ntwrk

volumes:
  jenkins_home:
networks:
  persistence_ntwrk:
    name: persistence_ntwrk
  jenkins_ntwrk:
    name: jenkins_ntwrk