version: '3.8'

services:
  persistence_app:
    build: .
    container_name: persistence_app
    env_file:
      - 'variables.env'
    ports:
      - "8082:8080"
    networks:
      - persistence_ntwrk
  postgres_db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: persistence
    ports:
      - "5432:5432"
    networks:
      - persistence_ntwrk
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - persistence_ntwrk

networks:
  persistence_ntwrk:
    name: persistence_ntwrk