version: '3.8'

services:
#  jenkins_app:
#    image: jenkins/jenkins:lts-jdk21
#    container_name: jenkins_app
#    ports:
#      - "8081:8080" # для доступа к веб-интерфейсу Jenkins
#      - "50000:50000" # для подключения агентов
#    volumes:
#      - jenkins_home:/var/jenkins_home
#    networks:
#      - persistence_ntwrk
  mybatis_vs_hibernate:
    build: .
    container_name: mybatis_vs_hibernate
    ports:
      - "8082:8080"
    networks:
      - persistence_ntwrk

volumes:
  jenkins_home:
networks:
  persistence_ntwrk:
    name: persistence_ntwrk