spring:
  application:
    name: persistence
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${db.schema}
    open-in-view: false
  liquibase:
    enabled: true
    change-log: db/changelog/changelog.yml
    default-schema: ${db.schema}
mybatis:
  type-handlers-package: com.pdp.persistence.dao.mybatis.handler
  mapper-locations: classpath:db/mapping/*-mapper.xml
db:
  schema: ${DATABASE_SCHEMA}
logging:
  level:
    root: info
    com.pdp.persistence: ${APP_LOG_LEVEL}