spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/persistence
    username: admin
    password: admin

db:
  schema: persistence_schema

server:
  port: 8090

logging:
  level:
    com.pdp.persistence: debug