apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin-application
spec:
  replicas: 2
  selector:
    matchLabels:
      project: myLabel
  template:
    metadata:
      labels:
        project: myLabel # service looks for these PODs labels
    spec:
      containers:
        - name: pgadmin-container
          image: dpage/pgadmin4
          ports:
            - containerPort: 5050
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@admin.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin

---
apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-service
  labels:
    env: dev
    owner: artyom
spec:
  type: NodePort
  selector:
    project: myLabel # selecting PODs with these labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 5050
      targetPort: 5050