apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence-deployment-2
  labels:
    app: persistence
spec:
  replicas: 3
  selector:
    matchLabels:
      project: myLabel
  template:
    metadata:
      labels:
        project: myLabel # service looks for these PODs labels
    spec:
      containers:
        - name: my-container-name
          image: booorisov/persistence:latest
          ports:
            - containerPort: 8080

        - name: not-my-container-name
          image: postgres:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-multi-pods-service
  labels:
    env: prod
    owner: booorisov
spec:
  type: LoadBalancer
  selector:
    project: myLabel # selecting PODs with these labels
  ports:
    - name: app-listener
      protocol: TCP
      port: 8080 # port on load balancer
      targetPort: 8080 # port on POD

    - name: not-my-app-listener
      protocol: TCP
      port: 8888
      targetPort: 8080
