apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts

spec:
  rules:
    - host: www.persistence-pdp.com
      http:
        paths:
        - pathType: Prefix
          path: "/login"
          backend:
            service:
              name: my-single-pod-service
              port:
                number: 5050