apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-autoscaling-deployment
  labels:
    app: postgres-autoscaling-application
    env: dev
    owner: artyom
spec:
  replicas: 2
  selector:
    matchLabels:
      project: postgres_autoscaling_label
  template:
    metadata:
      labels:
        project: postgres_autoscaling_label
    spec:
      containers:
        - name: postgres-container
          image: postgres
          ports:
            - containerPort: 5454
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: database

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: postgres-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postgres-autoscaling-deployment
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80