apiVersion: apps/v1
kind: Deployment
metadata:
  name: persistence-deploy-replicas
  labels:
    app : persistence
    env: prod
    owner: booorisov
spec:
  replicas: 3
  selector:
    matchLabels:
      project: something-replicas
  template:
    metadata:
      labels:
        project: something-replicas
    spec:
      containers:
        - name: persistence-replicas-container
          image: booorisov/persistence:latest
          ports:
            - containerPort: 8081