apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    env  : dev
    app  : database
    tier : backend
    owner: artyom
spec:
  containers:
    - name : postgres-container
      image: postgres
      ports:
        - containerPort: 5454
      env:
        - name : POSTGRES_USER
          value: user
        - name : POSTGRES_PASSWORD
          value: password
        - name : POSTGRES_DB
          value: database