version: '3.8'

services:
  jenkins_app:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins_app
    ports:
      - "8081:8080" # для доступа к веб-интерфейсу Jenkins
      - "50000:50000" # для подключения агентов
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins_ntwrk

volumes:
  jenkins_home:
    name: persistence_jenkins_home

networks:
  jenkins_ntwrk:
    name: jenkins_ntwrk