apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment-2
  labels:
    app: pgadmin-application-2
spec:
  selector:
    matchLabels:
      project: myLabel2
  template:
    metadata:
      labels:
        project: myLabel2
    spec:
      containers:
        - name: pgadmin-container
          image: dpage/pgadmin4
          ports:
            - containerPort: 5050
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: admin@admin.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: admin

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: postgres-autoscaling-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v2
    kind: Deployment
    name: pgadmin-deployment-2
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-autoscaler-service
  labels:
    env: dev
    owner: artyom
spec:
  type: LoadBalancer
  selector:
    project: myLabel2
  ports:
    - name: app-listener
      protocol: TCP
      port: 5050
      targetPort: 5050